export const VALID_FILE_TYPES = [
  // Markup/script types
  '.html',
  '.js',
  '.css',
  // Image types
  // https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types
  '.png',
  '.jpg',
  '.jpeg',
  '.jfif',
  '.pjpeg',
  '.pjp',
  '.gif',
  '.svg',
  '.webp',
  '.apng',
  '.avif',
  '.bmp',
  '.ico',
  '.cur',
  '.tif',
  '.tiff',
  // Video and audio types
  // https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers
  '.3gp',
  '.acc',
  '.flac',
  '.mpg',
  '.mpeg',
  '.mp3',
  '.mp4',
  '.m4a',
  '.m4v',
  '.m4p',
  '.oga',
  '.ogv',
  '.ogg',
  '.mov',
  '.wav',
  '.webm',
  // Data types
  '.csv',
  '.tsv',
  '.json',
  '.txt',
];
